### ISSUE TITLE
[Fabric] Crash on dedicated server load

### ISSUE THREAD

**Issue by raphydaphy** [modmuss50/JustSleep#5]
i think you failed

```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors!
        at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:45) ~[fabric-loader-0.4.3+build.134.jar:?]
        at net.fabricmc.loader.entrypoint.hooks.EntrypointServer.start(EntrypointServer.java:33) ~[fabric-loader-0.4.3+build.134.jar:?]
        at net.minecraft.class_3176.<init>(class_3176.java:99) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:912) [intermediary-server.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170) [fabric-loader-0.4.3+build.134.jar:?]
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:126) [fabric-loader-0.4.3+build.134.jar:?]
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26) [fabric-loader-0.4.3+build.134.jar:?]
        Suppressed: java.lang.NoClassDefFoundError: net/minecraft/class_310
                at net.fabricmc.fabric.impl.network.ClientSidePacketRegistryImpl.onRegister(ClientSidePacketRegistryImpl.java:71) ~[fabric-0.2.7+build.127.jar:?]
                at net.fabricmc.fabric.impl.network.PacketRegistryImpl.register(PacketRegistryImpl.java:57) ~[fabric-0.2.7+build.127.jar:?]
                at me.modmuss50.justsleep.JustSleep.onInitialize(JustSleep.java:67) ~[JustSleep-fabric-1.14-1.1.0.jar:?]
                at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.lambda$logErrors$0(EntrypointUtils.java:38) ~[fabric-loader-0.4.3+build.134.jar:?]
                at java.util.ArrayList.forEach(ArrayList.java:1540) ~[?:?]
                at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:36) ~[fabric-loader-0.4.3+build.134.jar:?]
                at net.fabricmc.loader.entrypoint.hooks.EntrypointServer.start(EntrypointServer.java:33) ~[fabric-loader-0.4.3+build.134.jar:?]
                at net.minecraft.class_3176.<init>(class_3176.java:99) ~[intermediary-server.jar:?]
                at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:912) [intermediary-server.jar:?]
                at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
                at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
                at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
                at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
                at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170) [fabric-loader-0.4.3+build.134.jar:?]
                at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:126) [fabric-loader-0.4.3+build.134.jar:?]
                at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26) [fabric-loader-0.4.3+build.134.jar:?]
        Caused by: java.lang.ClassNotFoundException: net.minecraft.class_310
                at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583) ~[?:?]
                at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
                at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
                at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:160) ~[fabric-loader-0.4.3+build.134.jar:?]
                at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
                ... 16 more
```

**Comment by steadyaero** [comment]
+1

**Comment by BingRazer** [comment]
+1
This was also above all the stuff raphydaphy posted, if it's relevant:

> [10:44:07] [main/WARN]: @Mixin target net.minecraft.class_423 was not found justsleep.client.json:MixinGuiChatSleeping
